name: data-start
on:
  workflow_dispatch:
jobs:
  data_start:
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - run: npm install
    - run: npm start
    - run: |
        git config user.email "ahmdee18@gmail.com"
        git config user.name "m-ahmadi"
        git add .
        git commit -m "data start"
        git push origin master
